/**
 * Auto-generated safe area implementation
 * Detected: none
 * Generated at: 2025-11-27T03:50:48.428Z
 *
 * DO NOT EDIT - This file is generated by scripts/detect-safe-area.js
 *
 * No react-native-safe-area-context found. Using pure JS fallback only.
 * Install react-native-safe-area-context for more accurate safe area values.
 */

export interface NativeSafeAreaInsets {
  top: number;
  bottom: number;
  left: number;
  right: number;
}

export const safeAreaType: "native" | "pure-js" = "pure-js";

export const hasSafeAreaPackage = false;

/**
 * Hook that returns null since react-native-safe-area-context is not installed.
 * The main useSafeAreaInsets hook will use pure JS fallback.
 */
export const useNativeSafeAreaInsets = (): NativeSafeAreaInsets | null => {
  return null;
};
